# Generated by Django 5.1.3 on 2024-11-22 15:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Habit name must be at least 3 characters long'), django.core.validators.MaxLengthValidator(100, 'Habit name cannot exceed 100 characters')])),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='daily', max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('target_days_per_week', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1, 'Target days must be at least 1'), django.core.validators.MaxValueValidator(7, 'Target days cannot exceed 7')])),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Habits',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('missed', 'Missed')], default='missed', max_length=20)),
                ('notes', models.TextField(blank=True, max_length=300, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_set', to='tracker.habit')),
            ],
            options={
                'verbose_name_plural': 'Progress Logs',
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
