# Generated by Django 5.1.3 on 2024-11-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='target_days_per_week',
        ),
    ]
